<?php

/**
 * Drupal hook for admin form
 * 
 */
function islandora_coalliance_manager_admin() {
  return "";
}

function islandora_admin_coalliance_admin_settings_submit($form, $form_values) {
  drupal_set_message("Custom form handler.");
}

/**
 * drupal hook
 * @return string
 */
function islandora_coalliance_manager_menu() {
  /* $items['islandora_co_manager'] = array(
    'title' => 'Islandora Manager',
    'type' => MENU_NORMAL_ITEM,
    //'page callback' => 'islandora_coalliance_manager_create_collection',
    //'page arguments' => array(2),
    'access arguments' => array('ingest new fedora objects'),
    ); */
  $items['islandora_co_manager/create_collection'] = array(
    'title' => 'Create Collection',
    //'type' => MENU_NORMAL_ITEM,
    'page arguments' => array(2),
    'page callback' => 'islandora_coalliance_manager_create_collection',
    'access arguments' => array('ingest new fedora objects'),
  );
  $items['islandora_co_manager/manage_policy_stream'] = array(
    'title' => 'Manage XACML Policies',
    //'type' => MENU_LOCAL_TASK,
    'page arguments' => array(2),
    'page callback' => 'islandora_coalliance_manager_manage_policy',
    'access arguments' => array('ingest new fedora objects'),
  );

  $items['admin/settings/islandora_admin_coalliance'] = array(
    'title' => 'Islandora Admin Co Client',
    'description' => 'For managing fedora collection creation and xacml Policies',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_coalliance_manager_admin_settings'),
    'access arguments' => array('administer site configuration'),
    //'file' => 'islandora.admin.coalliance.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 *
 * @return <type>
 */
function islandora_coalliance_manager_create_collection() {


  return drupal_get_form('islandora_coalliance_manager_create_collection_form');
}

/**
 *
 * @return array
 */
function islandora_coalliance_manager_get_existing_collections() {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  module_load_include('inc', 'fedora_repository', 'CollectionClass');
  $itql_query = 'select $object  $title from <#ri> where
$object <info:fedora/fedora-system:def/model#state> <info:fedora/fedora-system:def/model#Active>
and $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/islandora:collectionCModel>
and $object <info:fedora/fedora-system:def/model#label> $title';
  $collectionClass = new CollectionClass();
  $query_results = $collectionClass->getRelatedItems(NULL, $itql_query);
  $list_of_objects = islandora_coalliance_manager_itql_to_array($query_results);
  return $list_of_objects;
}

/**
 *
 * @param string $itql_query
 * @return <type>
 */
function islandora_coalliance_manager_get_related_objects($itql_query) {
  module_load_include('inc', 'fedora_repository', 'CollectionClass');
  $collectionClass = new CollectionClass();
  $query_results = $collectionClass->getRelatedItems(NULL, $itql_query);
  $list_of_objects = islandora_coalliance_manager_itql_to_array($query_results);
  return $list_of_objects;
}

function islandora_coalliance_manager_find_objects_by_pattern($pattern,$field){
  module_load_include('inc', 'fedora_repository', 'api/fedora_utils');
   $url = variable_get('fedora_base_url', 'http://localhost:8080/fedora');
   $url .= "/objects?query=$field~$pattern&pid=true&title=true&resultFormat=xml&maxResults=100";
   $results = do_curl($url);
   return $results;
}

/**
 *
 * @return <type>
 */
function islandora_coalliance_manager_create_collection_form() {
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  //need a way to generalize the below query so other installs can use this if desired.  We know these are the collection
  //cmodels available in coalliance.  we then filter by pid namespace for each institution so we only get there collection
  //objects
  $itql_query = 'select $object  $title from <#ri> where
$object <info:fedora/fedora-system:def/model#state> <info:fedora/fedora-system:def/model#Active>
and ($object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/codearl:codearlBasicCollection>
or $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/islandora:collectionCModel>
or $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/coccc:cocccBasicCollection>
or $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/codu:coduBasicCollection>
or $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/codru:codruBasicCollection>
or $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/wyu:wyuBasicCollection>
or $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/codr:codrBasicCollection>
or $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/codjm:codjmBasicCollection>
or $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/co:coBasicCollection>
or $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/cowjcpl:cowjcplBasicCollection>
or $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/gopig:gopigBasicCollection>
or $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/cogru:cogruBasicCollection>)
and $object <info:fedora/fedora-system:def/model#label> $title
order by $title';
  $existing_collections = islandora_coalliance_manager_get_related_objects($itql_query);
  $itql_query = 'select $object  $title from <#ri> where
$object <info:fedora/fedora-system:def/model#state> <info:fedora/fedora-system:def/model#Active>
and $object <info:fedora/fedora-system:def/model#hasModel> <info:fedora/fedora-system:ContentModel-3.0>
and $object <info:fedora/fedora-system:def/model#label> $title
order by $title';
  $existing_cmodels = islandora_coalliance_manager_get_related_objects($itql_query);
  
  $form = array();
  $roles = user_roles(TRUE);
  $select_roles = array();
  foreach ($roles as $key => $value) {
    $select_roles[$value] = $value;
  }
  $pid_namespaces = array(); // explode(' ',variable_get('fedora_pids_allowed', 'default: demo: changeme: Islandora: ilives: '));
  foreach (explode(' ', trim(variable_get('fedora_pids_allowed', 'default: demo: changeme: Islandora: ilives: ')))as $namespace) {
    $pid_namespaces[$namespace] = $namespace;
  }
  $existing_collections = islandora_coalliance_manager_limit_collections_by_namespace($existing_collections,$pid_namespaces);
  $existing_cmodels = islandora_coalliance_manager_limit_collections_by_namespace($existing_cmodels,$pid_namespaces);
  $form['collection_for_ingest'] = array(
    '#type' => 'select',
    '#title' => t('Choose a Collection to create this collection in'),
    '#options' => $existing_collections,
    '#required' => TRUE,
    '#description' => t('A list of existing collections.'),
  );
  $form['pid_namespace'] = array(
    '#type' => 'select',
    '#title' => t('Choose a namespace'),
    '#options' => $pid_namespaces,
    '#required' => TRUE,
    '#multiple' => FALSE,
    '#description' => t('Choose the namespace these objects will have when ingested'),
  );
  $form['allowed_cModels'] = array(
    '#type' => 'select',
    '#title' => t('Choose the content Models allowed'),
    '#options' => $existing_cmodels,
    '#required' => TRUE,
    '#multiple' => TRUE,
    '#description' => t('A list of existing Content Models.  These represent the types of objects that users will be allowed to ingest in this new collection'),
  );
  $form['collection_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Collection Name'),
    '#required' => TRUE,
    '#required' => TRUE,
    '#description' => t('A name or title for the new collection'),
  );
  $form['user_role'] = array(
    '#type' => 'select',
    '#title' => t('Choose the user role'),
    '#required' => TRUE,
    '#options' => $select_roles,
    '#description' => t('Choose the role that will be assigned to users.'),
  );
  $form['submitter_role'] = array(
    '#type' => 'select',
    '#title' => t('Choose the submitter role'),
    '#required' => TRUE,
    '#options' => $select_roles,
    '#description' => t('Choose the role that will be assigned to submitters.'),
  );
  $form['approver_role'] = array(
    '#type' => 'select',
    '#title' => t('Choose the approver role'),
    '#required' => TRUE,
    '#options' => $select_roles,
    '#description' => t('Choose the role that will be assigned to approvers (users that can approve objects).'),
  );
  $form['manager_role'] = array(
    '#type' => 'select',
    '#title' => t('Choose the manager role'),
    '#required' => TRUE,
    '#options' => $select_roles,
    '#description' => t('Choose the role that will be assigned to managers.'),
  );
  $form['adminstrator_role'] = array(
    '#type' => 'select',
    '#title' => t('Choose the creator role'),
    '#required' => TRUE,
    '#options' => $select_roles,
    '#description' => t('Choose the role that will be assigned to administrators.'),
  );

  $form['submit'] = array('#type' => 'submit', '#value' => t('Create'));

  return $form;
}

/**
 *
 * @param <type> $existing_collections
 * @param <type> $pid_namespaces
 */
function islandora_coalliance_manager_limit_collections_by_namespace($existing_collections, $pid_namespaces){
  $collections = array();
 foreach($existing_collections as $collection => $value){
    foreach($pid_namespaces as $key => $namespace){
      if(strpos($collection,$namespace)===0){
        $collections[$collection]=$value;
      }
    }
  }
  return $collections;
}

/**
 *
 * @param <array> $form
 * @param <array> $form_state
 *
 * form_state values array look like this
  'collection_for_ingest' => string 'uofm:ContentModelCollection' (length=27)
  'pid_namespace' => string 'cogru:' (length=6)
  'allowed_cModels' =>
  array
  'demo:XML_TO_HTMLDOC' => string 'demo:XML_TO_HTMLDOC' (length=19)
  'fedora-system:FedoraObject-3.0' => string 'fedora-system:FedoraObject-3.0' (length=30)
  'collection_name' => string 'test' (length=4)
  'user_role' => string 'authenticated user' (length=18)
  'submitter_role' => string 'administrator' (length=13)
  'approver_role' => string 'administrator' (length=13)
  'manager_role' => string 'viewer' (length=6)
  'adminstrator_role' => string 'viewer' (length=6)
  'op' => string 'Create' (length=6)
  'submit' => string 'Create' (length=6)
  'form_build_id' => string 'form-44eafb6e55be3ef1ea8bac3a285f256c' (length=37)
  'form_token' => string 'e7f4d0047ef69b74efb2840df9bb2499' (length=32)
  'form_id' => string 'islandora_coalliance_manager_create_collection_form' (length=51)
 *
 */
function islandora_coalliance_manager_create_collection_form_submit(&$form, &$form_state) {
  global $user;
  global $base_url;
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $collection_to_ingest_into = $form_state['values']['collection_for_ingest'];
  $new_collections_label = $form_state['values']['collection_name'];
  $user_role = $form_state['values']['user_role'];
  $submitter_role = $form_state['values']['submitter_role'];
  $manager_role = $form_state['values']['manager_role'];
  $adminstrator_role = $form_state['values']['adminstrator_role'];
  $pid_namespace = $form_state['values']['pid_namespace'];
  $pid_namespace = substr ($pid_namespace,0,strlen($pid_namespace)-1);
  $policy_stream = islandora_coalliance_manager_create_security_policy_stream($form, $form_state);
  $mods_stream = islandora_coalliance_manager_create_mods_stream($form, $form_state);
  //echo '<pre>'.$policy_stream.'</pre>';
  //exit();
  $collection_policy_stream = islandora_coalliance_manager_create_collection_policy_stream($form, $form_state); //searchterms and relationship is assumed here
  $new_pid = fedora_item::get_next_PID_in_namespace($pid_namespace);
  $query_stream = 'select $object $title from <#ri>
                             where $object <fedora-model:label> $title
                             and ($object <fedora-rels-ext:isMemberOf> <info:fedora/'.$new_pid.'>
                               or $object <fedora-rels-ext:isMemberOfCollection> <info:fedora/'.$new_pid.'>)
                             and $object <fedora-model:state> <info:fedora/fedora-system:def/model#Active>
                             order by $title';
  $new_object = fedora_item::ingest_new_item($new_pid, 'A', $new_collections_label, $user->name);
  $new_object->add_datastream_from_string($collection_policy_stream, 'COLLECTION_POLICY', 'COLLECTION_POLICY', 'text/xml', 'M', null);
  $new_object->add_datastream_from_string($policy_stream,'POLICY','POLICY','text/xml','M','added security policy stream');
  $new_object->add_datastream_from_string($policy_stream, 'CHILD_SECURITY', 'CHILD_SECURITY','text/xml','M','added child security stream');
  $new_object->add_datastream_from_string($mods_stream,'MODS','MODS','text/xml','M','added mods stream');
  $new_object->add_datastream_from_string($query_stream,'QUERY','QUERY', 'text/plain','M','added query stream');
  $new_object->add_relationship('isMemberOfCollection', $collection_to_ingest_into, RELS_EXT_URI);
  islandora_coalliance_manager_add_thumbnail_stream($new_object);
  $new_object->add_relationship('hasModel', 'islandora:collectionCModel', FEDORA_MODEL_URI);
  $return_url = '<a href="' . $base_url . '/fedora/repository/' . $new_pid . '/-/' . $new_collections_label . '"/>' . $new_collections_label . '</a>';
  $form_state['redirect'] = 'fedora/repository/' . $new_pid . '/-/'.$new_collections_label;
  ///formbuilder/edit/{object:pid}/{dsid}/{form name}
  drupal_set_message(t('Created new Collection %s', array('%s' => $new_collections_label . ' with pid ' . $new_pid)));
  return '';
}

/**
 *
 * @param <type> $new_object
 * @return <type>
 */
function islandora_coalliance_manager_add_thumbnail_stream(&$object){
    $filename = drupal_get_path('module', 'islandora_coalliance_manager') . '/images/TN.jpg';
  if (file_exists($filename)) {
    $object->add_datastream_from_file($filename,'TN','TN','image/jpg','M','added thumbnail stream');
  }
  else {
    drupal_set_message(t('Failed to add TN stream, could not load TN.jpg'), 'error');
    return FALSE;
  }
  return TRUE;
}

/**
 *
 * @param <type> $form
 * @param <type> $form_state
 * @return <type>
 */
function islandora_coalliance_manager_create_mods_stream($form, $form_state){
   $filename = drupal_get_path('module', 'islandora_coalliance_manager') . '/foxml/mods.xml';
  if (file_exists($filename)) {
    $contents = file_get_contents($filename);
    $mods_title = $form_state['values']['collection_name'];
    $contents = str_replace('mods_title', $mods_title, $contents);
    return $contents;
  }
  else {
    drupal_set_message(t('Failed to read security policy template file'), 'error');
    return ' ';
  }
}

/**
 *
 * @param <type> $form
 * @param <type> $form_state
 * @return <type>
 */
function islandora_coalliance_manager_create_security_policy_stream($form, $form_state) {
  $filename = drupal_get_path('module', 'islandora_coalliance_manager') . '/policy/Colorado_Alliance_Template.xml';
  if (file_exists($filename)) {
    $contents = file_get_contents($filename);
    $user_role = $form_state['values']['user_role'];
    $submitter_role = $form_state['values']['submitter_role'];
    $manager_role = $form_state['values']['manager_role'];
    $approvers_role = $form_state['values']['approver_role'];
    $adminstrator_role = $form_state['values']['adminstrator_role'];
    $contents = str_replace('submitter_role', $submitter_role, $contents);
    $contents = str_replace('manager_role', $manager_role, $contents);
    $contents = str_replace('user_role', $user_role, $contents);
    $contents = str_replace('approver_role', $approvers_role, $contents);
    return $contents;
  }
  else {
    drupal_set_message(t('Failed to read security policy template file'), 'error');
    return ' ';
  }
}

/**
 *
 * @param <array> $cmodels
 *
 */
function islandora_coalliance_manager_create_collection_policy_stream($form, $form_state) {
  $pid_namespace = $form_state['values']['pid_namespace'];
  $cmodels_for_collection_policy = $form_state['values']['allowed_cModels']; //array
  $cmodels_with_labels = $form['allowed_cModels']['#options'];
  $combined_cmodels_array = array(); //key is pid value is label
  foreach ($cmodels_for_collection_policy as $key => $value) {
    $combined_cmodels_array[$key] = $cmodels_with_labels[$key];
  }
  $dsid = 'ISLANDORACM';
  $filename = drupal_get_path('module', 'islandora_coalliance_manager') . '/foxml/collectionPolicyTemplate.xml';
  if (file_exists($filename)) {
    $xml = simplexml_load_file($filename);
    foreach ($combined_cmodels_array as $key => $value) {
      $cmodel = $xml->content_models->addChild('content_model');
      $cmodel->addAttribute('dsid', $dsid);
      $cmodel->addAttribute('name', $value);
      $cmodel->addAttribute('namespace', $pid_namespace . '1');
      $cmodel->addAttribute('pid', $key);
    }
  }
  else {
    drupal_set_message(t('Failed to read collection policy template file'), 'error');
    return;
  }
  return $xml->asXML();
}

function islandora_coalliance_manager_object_list_to_array($resultxml){
  $resultelements = simplexml_load_string($resultxml);
  if(!$resultelements){
     drupal_set_message(t('Error getting list of collection objects !e', array('!e' => $e->getMessage())), 'error');
    return;
  }
  $results = array();
   foreach ($resultelements->resultList->objectFields as $obj) {
     $results[(string)$obj->pid]=(string)$obj->title;
   }
   return $results;
}

/**
 *
 * @param <array> $query_results
 * @return string
 */
function islandora_coalliance_manager_itql_to_array($query_results) {
  try {
    $xml = new SimpleXMLElement($query_results);
  } catch (Exception $e) {
    drupal_set_message(t('Error getting list of collection objects !e', array('!e' => $e->getMessage())), 'error');
    return;
  }
  $list_of_objects = array();
  foreach ($xml->results->result as $result) {
    $a = $result->object->attributes();
    $temp = $a['uri'];
    $object = substr($temp, strrpos($temp, '/') + 1);
    $title = $result->title;
    $list_of_objects[$object] = (string) $title; //.' '.$object;
  }
  return $list_of_objects;
}

/**
 *
 * @return <type>
 */
function islandora_coalliance_manager_manage_policy() {
  return 'Work in progress please check back later';
}

/**
 *
 * @param <type> $path
 * @param <type> $arg
 * @return <type> 
 */
function islandora_coalliance_manager_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description' :
      return t('Fedora admin module.');
  }
}